DEV: Fix flaky test seen on CI (#236)
Error seen on CI:

```
Error:
TestRedisStore#test_solving_with_some_missing_version:
NameError: uninitialized constant Logster::RedisStore::Set
    lib/logster/redis_store.rb:396:in `clear_solved'
    lib/logster/redis_store.rb:99:in `solve'
    test/logster/test_redis_store.rb:742:in `test_solving_with_some_missing_version'
```

Ruby 3.1 needs `require 'set'`.